### ISSUE TITLE
Stopped working (Sort of)

### ISSUE THREAD

**Issue by Reetonzzz** [carlin-q-scott/browser-media-keys#44]
Everytime I launch Firefox this addon does not work and I have to disable it and reenable it again for it to work but if I close Firefox anc load it up the media keys won't work again.

**Comment by carlin-q-scott** [comment]
Thanks for reporting this issue.

When you open Firefox is it restoring a tab with a particular media page in it, such as youtube? I'm going to assume you're using Windows.

**Comment by Reetonzzz** [comment]
No it doesn't but I found something else out it seems that it only works if I have a video playing i.e When I have a video playing and enable the addon it will only work for that video. If I load a different video the addon will stop working again. I did try to delete the addon and install it againb but it still has the same problem. I was using the addon for about 2 months before this happened and I didnt have and the only thing that could have changed is something in a windows 10 update but I'm not sure.

**Comment by carlin-q-scott** [comment]
I recently updated the add-on to use a different method of receiving media key events from Windows so that's likely causing the issue even though I cannot reproduce it on any of my three Windows 10 computers.

A somewhat similar issue I can reproduce is that certain desktop media players like Spotify block the add-on when using the new method.

Would you be willing to install the previous version of the add-on to see if it resolves your issue? If you're interested, here are the steps:

1. Open the add-on manager (about:addons)
2. Click "Options" on the Media Keys extension
3. Disable updates via the gear icon at the top
4. Download and install v0.6.6 of the add-on: https://addons.mozilla.org/firefox/downloads/file/390122/media_keys-0.6.6-fx-windows.xpi?src=devhub
2.

**Comment by Reetonzzz** [comment]
Going back to v0.6.6 seems to have fixed it and it is all working fine now. I dont have any desktop media players like spotify unless you count the default windows media player but I dont ever use it so I doubt that was causing the issue.

**Comment by carlin-q-scott** [comment]
Thanks for verifying that for me. I have rolled back the released version to 0.6.6.

**Comment by oakkitten** [comment]
had a similar issue. if i went to youtube and hit play/pause media key, the youtube controls would show for a fraction of second, but nothing else happened. so the plugin was doing.. something. reenabling the plugin didn't work.

installing 0.6.6 from the link above worked fine

**Comment by Noitidart** [comment]
I'm using Win10 and it's not working for me even with disable/enable :(

**Comment by Noitidart** [comment]
Oh I restarted my browser today and it fixed it
