### ISSUE TITLE
Listening for global audio key events (XF86Audio) on Linux

### ISSUE THREAD

**Issue by davidjb** [carlin-q-scott/browser-media-keys#7]
I'm interested to see whether it's possible to make Firefox act like other applications on Linux that respond to global multimedia key presses.  Before I start getting into this, have you looked into this at all?  It'd be helpful to know straight up if the answer is that it's impossible.

Essentially, Linux applications respond to global key presses by, at least in GNOME-based environments, listening to specific DBus signals.  There's a Python-based example at https://gist.github.com/davidjb/e6cee3a040b1532e728d (from https://stackoverflow.com/questions/5744041/cant-get-dbus-signal-listener-to-work-in-c-with-gnome-multimedia-keys) that works, but obviously this would need to be made compatible with Firefox in JavaScript (if accessing dbus is possible).  C examples exist also, but I don't know how feasible this would be in an add-on.   I see that accessing the win32api was possible via ctypes for Windows, so presumably it's possible.

I'm interested in making this happen but wanted to see if you had any input first.

**Comment by carlin-q-scott** [comment]
I looked into supporting the hotkeys natively on linux only briefly and decided not to do it because there are multiple systems in place for handling hotkeys and I don't use my Ubuntu partition enough to miss using this add-on.

I'd be very happy to fulfill your future pull request though! And maybe even help with some testing on Unity if it's supported (it uses dbus from what I remember).

**Comment by davidjb** [comment]
Yep, Unity uses Dbus since it's all still essentially GNOME.  I'm using that as my computer environment so that's what I'll be testing on too.  Dbus support for would allow any GNOME-based desktop environment to work with the add-on; and give a fair body of knowledge to anyone who wanted to try adding support for other environments. 

So..where to start?  As I mentioned, I'm new to all this.  My first question is whether there's any restrictions on what an add-on can do or access outside of Firefox.  Beyond that, I've read that Firefox has a [optional requirement](https://www.mozilla.org/en-US/firefox/39.0a2/system-requirements/) on DBus so if going to DBus directly isn't possible, then perhaps an add-on can tap into that somehow.

**Comment by carlin-q-scott** [comment]
It sounds like DBus is a good target for supporting native media keys on Linux.

I think we have quite a bit of freedom because [this article](https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Using_js-ctypes/ctypes.open#Custom_Native_File) is about packaging custom shared libraries with an add-on and calling it using js-ctypes. This might be a good option even for the existing Windows hotkeys code because I could write most of it in C where it would be simpler and easier to read.

I suspect we don't have access to Firefox's interface with DBus directly but the DBus API might provide means to hook into the same "session". That might lead to the same situation I experienced while implementing this for Windows though; the best method for integrating with Windows media key events required injecting my key handler between Firefox and Windows which I doubt would fly with Mozilla. I even experimented with this technique and experienced a huge drop in responsiveness of the browser itself so it was likely not a viable solution even if it was the most "correct" solution for native applications.

As for general guidance... I think the MDN documentation is very good and important to read when working in JS. The biggest trouble I had with ctypes on Windows was figuring the type mappings between the Windows API and js-ctypes primitives. Also, setting up structs was confusing so it might help to compare my declarations in windowsHotkeys.js with the Windows API documentation for those same structs, types, etc.

**Comment by davidjb** [comment]
After much fiddling, I've got a proof of concept working!  I'm calling C code in GLib (which features GDBus bindings) from Firefox and having the callback into Javascript on a media button press.  Yes, I fully agree the most painful part has been figuring out Ctypes mappings!   Now I just have to see about cleaning it up and hooking it into your add-on.  

There's one part of my C code that requires a call to a multi-argument C function (eg use of an ellipsis in the function definition) & the examples I can find of others doing it don't appear to work for me.  A minor issue..and one I can work around if necessary. 

Also, I read on MDN (https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/js-ctypes_reference/Callbacks) about any callbacks from C need to be on the same thread.   Is this likely to affect things?    I can't get exact wording as MDN seems to be down right now.

**Comment by davidjb** [comment]
Semi-cleaned up example: https://gist.github.com/davidjb/e6cee3a040b1532e728d#file-gnome_mediakeys-js   For me, this runs in the console if I start the add-on debugger.  Pressing media keys produces a JS callback, printing the DBus call to the JS console.  Unfortunately, after several presses, such as 2, 4, or 8 (it varies), Firefox will crash with a segfault.  I'm not sure why yet, could be that the garbage collector is cleaning up the libraries or something similar.

Once I've got some time, I'll put it into a hotkeys file in this addon just like the existing windowshotkeys.js & see what happens.

**Comment by carlin-q-scott** [comment]
Wow, that's way more code than I was expecting. I was thinking the Linux APIs would be lighter than the Windows API. Way to go in hammering all that out so fast! I spent a couple weeks on the Windows code.

In regards to the SegFault, I found this statement near the bottom of the MDN article you linked to:
> Warning: You must store a reference to the callback object as long as the native code might call it. If you don't, the GC might collect the relevant data structures, and the browser will crash when native code attempts to invoke your callback." 

Seems to be the exact issue you're seeing and from looking at the gist code you posted, there doesn't appear to be a persistent reference to the callback in the js code. Just make `on_signal` a global and all should be good.

**Comment by davidjb** [comment]
This has been a lot more complicated than expected, but there's good news at the end!

For starters, to answer my original concern about the browser crashing from the example code, it *was* that a reference wasn't being kept, but the issue was that the ``on_signal`` function was being **wrapped** later, just before being passed to ``g_signal_connect_data``.  Because this wrapped function wasn't being referenced anywhere, the crashes were happening.  This solved this first issue.

Next up was trying to use a ChromeWorker (like the Windows hotkeys) to call out to js-ctypes.  Despite me being sure the code was correct (the code worked in the debugger, but not in the ChromeWorker), the browser continued to crash persistently on pressing a media key.  For me, logging was interesting from ChromeWorkers.  ``dump()`` didn't dump to the browser console, ``console.log`` doesn't work either (not even ``self.console.log``, which is apparantly available to Workers or importing the console library, nada).  The debugger was of no help as the code wasn't listed (even though it was running), and the only way to seemingly pick up general logic errors is to run ``jpm test``.  After all this, and seemingly having the code right, there was still some issue with the callback, crashing the browser on hitting a media key.  In absence of other information, I presume the issue must be threading-related since js-ctypes isn't thread safe in terms of callbacks.

The one error message that Firefox in verbose mode outputs before crashing:
```
JPM undefined [NPAPI 9421] ###!!! ABORT: Aborting on channel error.: file /build/firefox-BDQUHa/firefox-40.0~a2~hg20150603r262503/ipc/glue/MessageChannel.cpp, line 1662
[NPAPI 9421] ###!!! ABORT: Aborting on channel error.: file /build/firefox-BDQUHa/firefox-40.0~a2~hg20150603r262503/ipc/glue/MessageChannel.cpp, line 1662
```

Since the browser would keep crashing, I went and re-implemented my original code from a ChromeWorker in into a standard module (following the ``firefoxHotkeys.js`` example) and I'm pleased to say this works!  The debugger is now able to be used as well, which is a breath of fresh air, even inside the JS-based callback, which made it infinitely easier to deal with the ctypes structures and calling C code.

The pull request is at #9 and it works successfully for me on Ubuntu 15.04, 64bit.  It requires ``libglib2.0-0`` installed for the shared libraries on the host, but does a check to see if those libraries are available.  If they are, it starts using them; and if not, falls back to Firefox's standard key handlers.

As a side note, the amount of js-ctypes code that's been required to get to this point has been crazy.  But it works!

The only caveat is that if another DBus application (eg Rhythmbox) opens after FF starts listening to DBus, FF won't get any signals until that application exits.  This isn't a huge issue.   Normally, applications take precedence back (eg restart listening) if/when they re-gain focus.  So, what FF *should* do is restart listening upon regaining focus to one of its windows.  This might be too much overhead to worry about.  Either way, I'll open an issue to discuss.

PS Out of interest, what was your experience with the ChromeWorker for the Windows hot keys? I ask because having gone through the pain of trying to debug my Linux equivalent, I'm curious as to whether there's any sane way of debugging one.

**Comment by carlin-q-scott** [comment]
The reason I had to use a ChromeWorker for windowsHostkeys.js was because the windows code uses polling and I didn't want to interrupt the main FF thread for that. Since you're using a callback I guess it should be fine to run it on the main thread.

For debugging the ChromeWorker, I had to use the [Add-On Debugger](https://developer.mozilla.org/en-US/Add-ons/Add-on_Debugger#Enabling_the_Add-on_Debugger).

I'll pull your fork later tonight.

**Comment by davidjb** [comment]
Cool, thanks for the info.

As for the add-on debugger, that's what I used for most of my work.  The ChromeWorker code didn't show in the debugger though & any console-based logging failed to output anywhere when I was using the ChromeWorker, and the only way I could get anything out was using ``dump``.  Perhaps a weird nuance or a bug in the Developer Edition of FF.  Either way, worked around it and got it sorted in the end!

**Comment by carlin-q-scott** [comment]
Hmm, strange. I don't remember having that issue but I could have forgotten it. I definitely remember needing to use the add-on debugger to get certain code to show up. Perhaps it was any of the code? I always use it now just like you.
